export type { PermissionString } from "@bookph/core/features/pbac/domain/types/permission-registry";
export { Scope } from "@bookph/core/features/pbac/domain/types/permission-registry";
export { getAllPermissionStringsForScope } from "@bookph/core/features/pbac/domain/types/permission-registry";
export { PermissionCheckService } from "@bookph/core/features/pbac/services/permission-check.service";
export { FeaturesRepository } from "@bookph/core/features/flags/features.repository";
export { RoleService } from "@bookph/core/features/pbac/services/role.service";
export type { Role } from "@bookph/core/features/pbac/domain/models/Role";
export type { CreateRoleData, UpdateRolePermissionsData } from "@bookph/core/features/pbac/domain/models/Role";
export { isValidPermissionString } from "@bookph/core/features/pbac/domain/types/permission-registry";
export { isValidPermissionStringForScope } from "@bookph/core/features/pbac/domain/types/permission-registry";
